/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CertificateInfo {
  pfxPath: string
  pfxPassword: string
}

export interface Config {
  reason?: string
  location?: string
  contactInfo?: string
}

export declare function signPdf(certificate: CertificateInfo, pdfPath: string, config?: Config | undefined | null): Buffer
