/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PdfSigned {
  data: Array<number>
  constructor(data: Array<number>)
  credentialsProvider(s3Info: S3Info): PdfSigned
  toBuffer(): Buffer
  save(path: string, format: SaveFormat): Promise<void>
}

export interface CertificateInfo {
  pfxPath: string
  pfxPassword: string
}

export interface Config {
  reason?: string
  location?: string
  contactInfo?: string
}

export interface S3Info {
  bucket: string
  accessKey: string
  secretKey: string
  endpoint: string
  region?: string
  providerName?: string
}

export declare const enum SaveFormat {
  File = 'File',
  S3 = 'S3'
}

export declare function signPdf(certificate: CertificateInfo, pdfData: Buffer, config?: Config | undefined | null): PdfSigned

export declare function signPdfWithPath(certificate: CertificateInfo, pdfPath: string, config?: Config | undefined | null): PdfSigned
